// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnEgxRSGSxRQmJQKnCxe4yFiTFcuntS9U',
    appId: '1:827894264079:web:c698fa57ed9874b68e8e7a',
    messagingSenderId: '827894264079',
    projectId: 'tracebc-c6271',
    authDomain: 'tracebc-c6271.firebaseapp.com',
    storageBucket: 'tracebc-c6271.firebasestorage.app',
    measurementId: 'G-94LHTYTDNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHidfTU5r3jUEz0RncWnPwj1C3WIs9_xw',
    appId: '1:827894264079:android:e9829feb6ea2adf08e8e7a',
    messagingSenderId: '827894264079',
    projectId: 'tracebc-c6271',
    storageBucket: 'tracebc-c6271.firebasestorage.app',
  );

}